public class BuiltIn {
    public static void main(String[]args){
        //Math walw...
       /*  System.out.println(Math.sqrt());
        System.out.println(Math.cbrt());
        System.out.println(Math.floor());   //greatest integer function...
        System.out.println(Math.ceil());    //smallest integer function...
        System.out.println(Math.min());     //minimum function...
        System.out.println(Math.max());     //maximum function... */
    }
}
